"""The language-neutral host-adapter contract and the Python adapter.

An adapter extracts comment units and host anchors from one host language
and applies the conservative exclusion policy. The contract is deliberately
small so a later adapter for another language changes nothing outside this
module: `extract_comments`, `resolve_anchor`, and `file_excluded`.

The Python adapter uses only :mod:`tokenize` and :mod:`ast`. Docstrings are
never comment tokens, so they are excluded by construction.
"""

from __future__ import annotations

import ast
import io
import re
import tokenize
from dataclasses import dataclass
from typing import Protocol

from itws.comments.records import CommentUnit, HostAnchor
from itws.model import SourceSpan, content_hash

#: Comment lines that configure a tool rather than inform a reader.
DIRECTIVE_RE = re.compile(
    r"^\s*(?:type:|noqa\b|pylint[:\s]|mypy:|ruff[:\s]|fmt:|isort:|pragma\b|"
    r"coding[:=])"
)

#: Signals, in a file's first lines, that the whole file is generated.
GENERATED_RE = re.compile(r"generated by|do not edit", re.IGNORECASE)

#: Signals that a file-leading comment block is a legal banner.
LEGAL_RE = re.compile(r"copyright|licen[cs]e|spdx|all rights reserved", re.IGNORECASE)

#: How many leading lines the generated-file scan reads.
GENERATED_SCAN_LINES = 10


class HostAdapter(Protocol):
    """What a host language must supply to join the §4.13 surface."""

    language: str

    def extract_comments(self, source: str, path: str) -> list[CommentUnit]:
        """Return every comment unit with its span and exclusion state."""

    def resolve_anchor(self, source: str, path: str, span: SourceSpan) -> HostAnchor:
        """Return the host anchor for a comment at ``span``."""

    def file_excluded(self, source: str) -> str:
        """Return the reason the whole file is excluded, or an empty string."""


@dataclass(frozen=True)
class _Construct:
    label: str
    start_line: int
    end_line: int


class PythonAdapter:
    """The standard-library Python adapter."""

    language = "python"

    def file_excluded(self, source: str) -> str:
        head = source.splitlines()[:GENERATED_SCAN_LINES]
        for line in head:
            if line.lstrip().startswith("#") and GENERATED_RE.search(line):
                return "generated file notice in the leading lines"
        return ""

    def extract_comments(self, source: str, path: str) -> list[CommentUnit]:
        file_reason = self.file_excluded(source)
        raw: list[tuple[int, int, str, bool]] = []
        code_lines: set[int] = set()
        try:
            tokens = list(tokenize.generate_tokens(io.StringIO(source).readline))
        except (tokenize.TokenError, SyntaxError, IndentationError):
            return []
        for token in tokens:
            if token.type == tokenize.COMMENT:
                raw.append(
                    (token.start[0], token.start[1], token.string, False)
                )
            elif token.type not in (
                tokenize.NL,
                tokenize.NEWLINE,
                tokenize.INDENT,
                tokenize.DEDENT,
                tokenize.ENDMARKER,
                tokenize.ENCODING,
            ):
                code_lines.add(token.start[0])

        units: list[CommentUnit] = []
        group: list[tuple[int, int, str]] = []

        def flush() -> None:
            if not group:
                return
            start = group[0][0]
            end = group[-1][0]
            raw_text = "\n".join(item[2] for item in group)
            text = "\n".join(_strip_marker(item[2]) for item in group).strip()
            excluded, reason = self._exclusion(group, start, source, file_reason)
            units.append(
                CommentUnit(
                    span=SourceSpan(path, start, end),
                    text=text,
                    raw_text=raw_text,
                    trailing=False,
                    excluded=excluded,
                    exclusion_reason=reason,
                )
            )
            group.clear()

        for line, column, text, _ in raw:
            trailing = line in code_lines
            if trailing:
                flush()
                stripped = _strip_marker(text).strip()
                excluded, reason = self._exclusion(
                    [(line, column, text)], line, source, file_reason
                )
                units.append(
                    CommentUnit(
                        span=SourceSpan(path, line, line),
                        text=stripped,
                        raw_text=text,
                        trailing=True,
                        excluded=excluded,
                        exclusion_reason=reason,
                    )
                )
                continue
            if group and (line != group[-1][0] + 1 or column != group[-1][1]):
                flush()
            group.append((line, column, text))
        flush()
        return units

    def _exclusion(
        self,
        group: list[tuple[int, int, str]],
        start: int,
        source: str,
        file_reason: str,
    ) -> tuple[bool, str]:
        if file_reason:
            return True, file_reason
        first_text = group[0][2]
        if start == 1 and first_text.startswith("#!"):
            return True, "shebang line"
        body = _strip_marker(first_text)
        if DIRECTIVE_RE.match(body):
            return True, "tool directive"
        joined = " ".join(_strip_marker(text) for _, _, text in group)
        if start <= 2 and LEGAL_RE.search(joined):
            return True, "legal banner"
        return False, ""

    def resolve_anchor(self, source: str, path: str, span: SourceSpan) -> HostAnchor:
        constructs = _constructs(source)
        lines = source.splitlines()

        chosen: _Construct | None = None
        # A comment directly above a construct anchors to that construct.
        following = [
            construct
            for construct in constructs
            if 0 <= construct.start_line - span.end_line <= 2
        ]
        if following:
            chosen = min(following, key=lambda item: item.start_line)
        else:
            containing = [
                construct
                for construct in constructs
                if construct.start_line <= span.start_line <= construct.end_line
            ]
            if containing:
                chosen = max(containing, key=lambda item: item.start_line)

        if chosen is None:
            chosen = _Construct("module", 1, max(len(lines), 1))
        segment = "\n".join(lines[chosen.start_line - 1 : chosen.end_line])
        return HostAnchor(
            path=path,
            start_line=chosen.start_line,
            end_line=chosen.end_line,
            construct=chosen.label,
            anchor_hash=content_hash(segment),
        )


def _strip_marker(comment: str) -> str:
    return re.sub(r"^\s*#\s?", "", comment)


def _constructs(source: str) -> list[_Construct]:
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []
    found: list[_Construct] = []

    def visit(node: ast.AST, prefix: str) -> None:
        for child in ast.iter_child_nodes(node):
            label = ""
            if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                label = f"function {prefix}{child.name}"
            elif isinstance(child, ast.ClassDef):
                label = f"class {prefix}{child.name}"
            if label:
                start = min(
                    [child.lineno]
                    + [decorator.lineno for decorator in child.decorator_list]
                )
                found.append(_Construct(label, start, child.end_lineno or child.lineno))
                visit(child, prefix + child.name + ".")
            else:
                visit(child, prefix)

    visit(tree, "")
    return sorted(found, key=lambda item: (item.start_line, item.end_line))


_ADAPTERS: dict[str, HostAdapter] = {"python": PythonAdapter()}


def get_adapter(language: str) -> HostAdapter | None:
    """Return the registered adapter for ``language``, or ``None``."""
    return _ADAPTERS.get(language)
