"""Curated §1.6 navigation metadata for every ITWS rule.

This module is the authoring aid behind ``tools/itws_annotate.py``. The
Markdown files remain authoritative: the tool writes these values into the
rule blocks, and the parser then reads them back from the Markdown. Nothing
downstream imports this table.

Each entry maps a permanent rule ID to::

    (target, constructs, chunks, slots, layers, context, rewrite,
     reads, writes, relations)

``constructs`` records a condition the rule's normative statement already
states. Every other field is a navigation aid (§1.6).
"""

from __future__ import annotations

# fmt: off
ANNOTATIONS: dict[str, tuple[str, str, str, str, str, str, str, str, str, str]] = {
    # --- Part 2: words and vocabulary --------------------------------------
    "2.1.1": ("term", "admitted-term", "any", "any", "both", "document", "review",
              "chunk-text, term-ledger", "chunk-text, term-ledger",
              "constrains 2.1.2; pairs-with 5.2.2"),
    "2.1.2": ("term", "admitted-term", "any", "any", "both", "document", "candidate",
              "chunk-text, term-ledger", "chunk-text",
              "requires 2.1.1; pairs-with 6.5.1"),
    "2.1.3": ("word", "verb", "any", "any", "plain", "local", "mechanical",
              "chunk-text", "chunk-text", "pairs-with 3.10.6"),
    "2.1.4": ("term", "acronym", "any", "any", "both", "document", "candidate",
              "chunk-text, term-ledger", "chunk-text, term-ledger",
              "requires 2.3.1; constrains 2.1.5"),
    "2.1.5": ("term", "acronym", "any", "any", "both", "document", "candidate",
              "chunk-text, term-ledger", "chunk-text", "requires 2.1.4"),
    "2.2.1": ("term", "domain-term", "any", "any", "both", "document", "review",
              "chunk-text, term-ledger", "term-ledger",
              "requires 2.3.1; pairs-with 2.1.1"),
    "2.3.1": ("term", "domain-term", "definition", "any", "both", "document", "review",
              "chunk-text, term-ledger", "chunk-text, term-ledger",
              "requires 2.2.1; constrains 2.3.2; pairs-with 4.4.2"),
    "2.3.2": ("term", "definition", "definition", "any", "both", "document", "review",
              "chunk-text, term-ledger", "chunk-text", "requires 2.3.1"),
    "2.3.3": ("term", "domain-term", "any", "any", "both", "document", "review",
              "chunk-text, term-ledger", "chunk-text",
              "requires 2.3.1; constrains 4.7.2"),
    "2.3.4": ("term", "definition", "definition", "any", "exact", "local", "review",
              "chunk-text", "chunk-text", "constrains 2.4.1"),
    "2.4.1": ("term", "definition", "definition", "any", "exact", "document", "review",
              "chunk-text, term-ledger", "chunk-text", "requires 2.3.4"),
    "2.4.2": ("term", "definition", "definition", "any", "exact", "document", "review",
              "chunk-text, term-ledger", "chunk-text", "requires 2.3.2"),
    "2.4.3": ("term", "definition", "definition", "any", "plain", "local", "candidate",
              "chunk-text", "chunk-text", "pairs-with 2.3.4"),
    "2.4.4": ("term", "definition", "definition", "any", "plain", "local", "mechanical",
              "chunk-text", "chunk-text", "constrains 2.4.5; pairs-with 4.8.1"),
    "2.4.5": ("term", "definition", "definition", "any", "exact", "local", "review",
              "chunk-text", "chunk-text", "requires 2.3.2"),
    "2.5.1": ("term", "admitted-term", "any", "any", "exact", "collection", "review",
              "chunk-text, term-ledger", "chunk-text", "requires 2.3.1"),
    "2.5.2": ("term", "admitted-term", "definition", "any", "exact", "collection",
              "candidate", "chunk-text, term-ledger", "chunk-text", "requires 2.5.1"),
    "2.5.3": ("term", "admitted-term", "any", "any", "plain", "collection", "prohibited",
              "term-ledger", "none", "pairs-with 2.5.1"),
    "2.6.1": ("sentence", "domain-term", "any", "any", "plain", "local", "candidate",
              "chunk-text", "chunk-text", "requires 2.2.1"),
    "2.6.2": ("term", "name", "any", "any", "plain", "document", "candidate",
              "chunk-text, term-ledger", "chunk-text", "pairs-with 2.7.1"),
    "2.6.3": ("sentence", "prohibited-phrase, measurement", "any", "any", "plain",
              "local", "candidate", "chunk-text", "chunk-text",
              "constrains 5.4.2; pairs-with 2.6.4"),
    "2.6.4": ("word", "prohibited-phrase", "any", "any", "plain", "local", "mechanical",
              "chunk-text", "chunk-text", "pairs-with 2.6.3"),
    "2.6.5": ("sentence", "verb", "any", "any", "plain", "document", "review",
              "chunk-text, term-ledger", "chunk-text", "requires 2.3.4"),
    "2.6.6": ("sentence", "prohibited-phrase", "any", "any", "plain", "local",
              "mechanical", "chunk-text", "chunk-text", "validates 4.9.1"),
    "2.6.7": ("sentence", "prohibited-phrase", "any", "any", "plain", "local",
              "mechanical", "chunk-text", "chunk-text", "pairs-with 4.2.2"),
    "2.6.8": ("sentence", "citation, claim", "any", "any", "exact", "local", "review",
              "chunk-text, citation-ledger", "chunk-text",
              "requires 5.4.3; pairs-with 5.4.5"),
    "2.6.9": ("sentence", "speculation", "any", "any", "exact", "local", "review",
              "chunk-text", "chunk-text", "pairs-with 7.3.2"),
    "2.6.10": ("sentence", "connective", "any", "any", "plain", "neighboring",
               "mechanical", "chunk-text", "chunk-text", "requires 3.8.3"),
    "2.6.11": ("sentence", "tool-artifact", "any", "any", "plain", "local", "mechanical",
               "chunk-text", "chunk-text", "none"),
    "2.7.1": ("term", "name", "any", "any", "plain", "document", "candidate",
              "chunk-text, term-ledger", "chunk-text, term-ledger", "requires 2.3.1"),
    "2.7.2": ("term", "name", "any", "any", "plain", "document", "review",
              "chunk-text", "chunk-text", "pairs-with 2.7.1"),
    "2.7.3": ("term", "name", "any", "any", "both", "document", "candidate",
              "chunk-text, term-ledger", "chunk-text, term-ledger",
              "pairs-with 2.1.2; pairs-with 5.2.2"),
    "2.7.4": ("citation", "citation, name", "any", "any", "exact", "local", "review",
              "chunk-text, citation-ledger", "chunk-text", "pairs-with 5.4.1"),

    # --- Part 3: sentences --------------------------------------------------
    "3.1.1": ("sentence", "any", "any", "any", "plain", "local", "candidate",
              "chunk-text", "chunk-text", "requires 3.1.3; constrains 3.1.4"),
    "3.1.2": ("sentence", "claim", "any", "any", "exact", "local", "candidate",
              "chunk-text", "chunk-text", "requires 3.1.3; constrains 3.1.4"),
    "3.1.3": ("sentence", "equation", "any", "any", "exact", "local", "mechanical",
              "chunk-text", "none", "validates 3.1.1; validates 3.1.2"),
    "3.1.4": ("sentence", "claim", "any", "any", "exact", "local", "review",
              "chunk-text, exact-item-ledger", "chunk-text",
              "constrains 3.1.1; constrains 3.1.2; requires 5.1.1"),
    "3.2.1": ("sentence", "any", "any", "any", "plain", "local", "review",
              "chunk-text", "chunk-text", "pairs-with 4.1.1"),
    "3.2.2": ("sentence", "claim", "any", "any", "exact", "local", "review",
              "chunk-text, claim-ledger", "chunk-text", "requires 3.2.1"),
    "3.3.1": ("sentence", "verb", "any", "any", "plain", "local", "candidate",
              "chunk-text", "chunk-text", "pairs-with 3.3.2"),
    "3.3.2": ("sentence", "pronoun", "any", "any", "plain", "local", "candidate",
              "chunk-text", "chunk-text", "pairs-with 3.3.1"),
    "3.4.1": ("sentence", "verb", "any", "any", "plain", "local", "candidate",
              "chunk-text", "chunk-text", "constrains 3.4.2"),
    "3.4.2": ("sentence", "verb, hedge", "any", "any", "exact", "local", "candidate",
              "chunk-text", "chunk-text", "requires 3.4.1; pairs-with 5.6.1"),
    "3.5.1": ("sentence", "noun-cluster", "any", "any", "plain", "local", "candidate",
              "chunk-text", "chunk-text", "constrains 3.5.2"),
    "3.5.2": ("sentence", "noun-cluster, admitted-term", "any", "any", "plain",
              "document", "mechanical", "chunk-text, term-ledger", "none",
              "requires 3.5.1"),
    "3.6.1": ("sentence", "pronoun", "any", "any", "plain", "neighboring", "candidate",
              "chunk-text", "chunk-text", "constrains 3.6.2"),
    "3.6.2": ("sentence", "pronoun", "any", "any", "plain", "local", "mechanical",
              "chunk-text", "chunk-text", "requires 3.6.1"),
    "3.7.1": ("sentence", "word", "any", "any", "exact", "local", "candidate",
              "chunk-text", "chunk-text", "pairs-with 3.7.4"),
    "3.7.2": ("sentence", "list", "any", "any", "exact", "local", "mechanical",
              "chunk-text", "chunk-text", "pairs-with 5.5.1"),
    "3.7.3": ("sentence", "word", "any", "any", "plain", "local", "candidate",
              "chunk-text", "chunk-text", "pairs-with 3.9.1"),
    "3.7.4": ("sentence", "generalization", "any", "any", "exact", "local", "review",
              "chunk-text", "chunk-text", "pairs-with 7.4.1"),
    "3.8.1": ("sentence", "any", "any", "any", "plain", "local", "mechanical",
              "chunk-text", "chunk-text", "pairs-with 3.2.1"),
    "3.8.2": ("sentence", "list", "any", "any", "plain", "local", "mechanical",
              "chunk-text", "chunk-text", "none"),
    "3.8.3": ("sentence", "connective", "any", "any", "plain", "local", "candidate",
              "chunk-text", "chunk-text", "constrains 2.6.10"),
    "3.9.1": ("sentence", "hedge", "any", "any", "exact", "local", "mechanical",
              "chunk-text", "chunk-text", "requires 5.6.1"),
    "3.9.2": ("sentence", "hedge, claim", "any", "any", "exact", "local", "candidate",
              "chunk-text, claim-ledger", "chunk-text", "requires 5.6.1"),
    "3.10.1": ("list", "list", "any", "any", "plain", "local", "review",
               "chunk-text", "chunk-text", "pairs-with 2.6.4"),
    "3.10.2": ("sentence", "prohibited-phrase", "any", "any", "plain", "local",
               "mechanical", "chunk-text", "chunk-text", "pairs-with 2.6.4"),
    "3.10.3": ("sentence", "any", "any", "any", "plain", "local", "candidate",
               "chunk-text", "chunk-text", "pairs-with 3.8.3"),
    "3.10.4": ("sentence", "prohibited-phrase", "any", "any", "plain", "local",
               "mechanical", "chunk-text", "chunk-text", "pairs-with 2.6.4"),
    "3.10.5": ("sentence", "quantity", "any", "any", "exact", "local", "candidate",
               "chunk-text", "chunk-text", "requires 5.4.2"),
    "3.10.6": ("sentence", "prohibited-phrase, verb", "any", "any", "plain", "local",
               "mechanical", "chunk-text", "chunk-text", "pairs-with 2.1.3"),

    # --- Part 4: structure --------------------------------------------------
    "4.1.1": ("chunk", "any", "any", "any", "both", "local", "review",
              "chunk-text", "chunk-text", "constrains 4.2.2; pairs-with 7.3.1"),
    "4.2.1": ("sentence", "any", "any", "any", "plain", "local", "candidate",
              "chunk-text", "chunk-text", "pairs-with 4.2.2"),
    "4.2.2": ("chunk", "any", "any", "any", "plain", "local", "candidate",
              "chunk-text", "chunk-text", "requires 4.1.1"),
    "4.2.3": ("section", "section", "any", "any", "plain", "section", "review",
              "chunk-text, heading", "chunk-text", "requires 4.2.2; pairs-with 4.7.1"),
    "4.2.4": ("document", "any", "any", "Summary", "plain", "document", "review",
              "chunk-text, skeleton-order", "chunk-text",
              "requires 4.4.1; pairs-with 4.4.3"),
    "4.3.1": ("declaration", "declaration", "any", "any", "exact", "document",
              "prohibited", "declaration-block", "none", "constrains 4.4.1"),
    "4.3.2": ("document", "any", "any", "any", "both", "document", "review",
              "chunk-text, skeleton-order", "chunk-text", "requires 4.3.1"),
    "4.3.3": ("document", "section", "any", "any", "both", "document", "candidate",
              "heading, skeleton-order", "heading, skeleton-order", "requires 4.4.1"),
    "4.4.1": ("document", "section", "any", "any", "both", "document", "candidate",
              "heading, skeleton-order", "heading, skeleton-order",
              "requires 4.3.1; constrains 4.3.3"),
    "4.4.2": ("document", "domain-term", "any", "any", "both", "document", "review",
              "chunk-text, term-ledger, skeleton-order", "chunk-text",
              "requires 2.3.1"),
    "4.4.3": ("document", "claim", "any", "any", "both", "document", "review",
              "chunk-text, exact-item-ledger", "chunk-text",
              "requires 5.1.2; pairs-with 4.2.4"),
    "4.5.1": ("heading", "heading", "any", "any", "plain", "section", "candidate",
              "heading, chunk-text", "heading", "pairs-with 4.10.1"),
    "4.6.1": ("chunk", "bounded-block", "any", "any", "exact", "section", "review",
              "chunk-text", "chunk-text", "constrains 4.6.3; pairs-with 6.3.1"),
    "4.6.2": ("bounded-block", "bounded-block", "any", "any", "both", "local",
              "mechanical", "chunk-text", "chunk-text", "validates 4.6.1"),
    "4.6.3": ("document", "bounded-block", "any", "any", "both", "document", "review",
              "chunk-text", "chunk-text", "requires 4.6.1"),
    "4.7.1": ("section", "section", "any", "any", "plain", "section", "candidate",
              "chunk-text, heading", "chunk-text", "pairs-with 4.2.3"),
    "4.7.2": ("section", "cross-reference", "any", "any", "plain", "document",
              "candidate", "chunk-text, cross-reference-ledger", "chunk-text",
              "constrains 2.3.3"),
    "4.7.3": ("sentence", "cross-reference", "any", "any", "both", "document",
              "mechanical", "chunk-text, cross-reference-ledger",
              "chunk-text, cross-reference-ledger", "requires 4.7.2"),
    "4.8.1": ("document", "domain-term", "any", "any", "both", "document", "review",
              "chunk-text, term-ledger", "chunk-text",
              "requires 2.3.1; pairs-with 4.4.2"),
    "4.8.2": ("section", "section", "any", "any", "plain", "section", "candidate",
              "chunk-text", "chunk-text", "constrains 4.8.3"),
    "4.8.3": ("section", "section", "any", "any", "plain", "section", "candidate",
              "chunk-text", "chunk-text", "requires 4.8.2"),
    "4.9.1": ("sentence", "prohibited-phrase", "any", "any", "plain", "local",
              "candidate", "chunk-text", "chunk-text",
              "constrains 4.9.2; pairs-with 2.6.6"),
    "4.9.2": ("chunk", "any", "context", "any", "both", "section", "review",
              "chunk-text", "chunk-text", "requires 4.9.1"),
    "4.9.3": ("sentence", "any", "any", "any", "both", "section", "review",
              "chunk-text", "chunk-text", "requires 4.9.1; requires 4.9.2"),
    "4.10.1": ("heading", "heading", "any", "any", "plain", "local", "mechanical",
               "heading", "heading", "validates 4.5.1"),
    "4.10.2": ("sentence", "any", "any", "any", "plain", "local", "candidate",
               "chunk-text", "chunk-text", "pairs-with 2.3.1"),
    "4.10.3": ("list", "list", "any", "any", "plain", "local", "candidate",
               "chunk-text", "chunk-text", "requires 4.1.1"),
    "4.10.4": ("table", "table", "any", "any", "plain", "local", "review",
               "chunk-text", "chunk-text", "pairs-with 5.5.1"),
    "4.10.5": ("document", "any", "any", "any", "plain", "local", "mechanical",
               "chunk-text", "chunk-text", "none"),
    "4.10.6": ("section", "section", "any", "any", "plain", "section", "review",
               "chunk-text", "chunk-text", "pairs-with 6.5.4"),
    "4.11.1": ("heading", "title", "any", "any", "exact", "document", "candidate",
               "heading", "heading", "pairs-with 4.5.1"),
    "4.11.2": ("heading", "title, user-journey", "any", "any", "exact", "document",
               "candidate", "heading", "heading", "requires 4.11.5"),
    "4.11.3": ("heading", "title", "any", "any", "exact", "document", "candidate",
               "heading", "heading", "requires 4.11.5"),
    "4.11.4": ("heading", "title", "any", "any", "exact", "document", "candidate",
               "heading", "heading", "requires 4.11.13"),
    "4.11.5": ("document", "declaration", "any", "Classification", "exact", "document",
               "review", "declaration-block", "declaration-block", "constrains 4.11.6"),
    "4.11.6": ("document", "requirement", "any", "any", "exact", "document", "review",
               "chunk-text, evidence-ledger", "chunk-text", "requires 4.11.5"),
    "4.11.7": ("document", "invariant", "any", "any", "exact", "document", "review",
               "chunk-text", "chunk-text", "requires 4.11.5"),
    "4.11.8": ("document", "invariant", "any", "any", "exact", "document", "mechanical",
               "chunk-text, exact-item-ledger", "chunk-text, exact-item-ledger",
               "constrains 4.11.9"),
    "4.11.9": ("document", "invariant", "any", "any", "exact", "collection",
               "prohibited", "chunk-text, exact-item-ledger", "none",
               "requires 4.11.8"),
    "4.11.10": ("document", "any", "any", "any", "both", "document", "review",
                "chunk-text", "chunk-text", "requires 4.3.2"),
    "4.11.11": ("document", "any", "any", "any", "exact", "collection", "review",
                "chunk-text", "chunk-text", "constrains 4.11.14"),
    "4.11.12": ("document", "parent-link", "any", "any", "exact", "collection",
                "prohibited", "chunk-text", "none", "constrains 4.11.13"),
    "4.11.13": ("document", "parent-link", "any", "any", "exact", "collection",
                "prohibited", "chunk-text", "none", "requires 4.11.12"),
    "4.11.14": ("document", "any", "any", "any", "exact", "collection", "prohibited",
                "chunk-text", "none", "requires 4.11.11"),
    "4.11.15": ("document", "user-journey", "any", "any", "exact", "collection",
                "review", "chunk-text", "chunk-text", "requires 4.11.19"),
    "4.11.16": ("document", "user-journey", "any", "any", "exact", "collection",
                "prohibited", "chunk-text", "none", "requires 4.11.15"),
    "4.11.17": ("chunk", "any", "any", "any", "exact", "local", "review",
                "chunk-text", "chunk-text", "constrains 5.9.1"),
    "4.11.18": ("document", "user-journey", "any", "any", "exact", "document", "review",
                "chunk-text", "chunk-text", "requires 4.11.2"),
    "4.11.19": ("document", "user-journey", "any", "any", "exact", "document", "review",
                "chunk-text", "chunk-text", "requires 4.11.18"),
    "4.11.20": ("document", "any", "any", "any", "exact", "document", "review",
                "chunk-text", "chunk-text", "requires 4.11.3"),
    "4.11.21": ("document", "any", "any", "any", "exact", "document", "review",
                "chunk-text", "chunk-text", "requires 4.11.20"),
    "4.12.1": ("document", "any", "any", "any", "plain", "document", "candidate",
               "heading, chunk-text", "heading, chunk-text",
               "requires 4.2.2; requires 4.2.3; pairs-with 4.5.1"),
    "4.12.2": ("document", "any", "any", "any", "plain", "document", "review",
               "heading, chunk-text, exact-item-ledger", "heading, chunk-text",
               "requires 4.12.1; requires 4.4.3; pairs-with 7.4.1"),
    "4.12.3": ("sentence", "any", "any", "any", "both", "document", "review",
               "chunk-text, exact-item-ledger, claim-ledger", "chunk-text",
               "requires 4.12.2; requires 3.1.4; requires 7.2.1"),
    "4.12.4": ("sentence", "any", "any", "any", "plain", "document", "candidate",
               "chunk-text, cross-reference-ledger", "chunk-text",
               "requires 4.12.1; pairs-with 4.7.1; pairs-with 4.7.2"),

    # --- Part 4: maintenance comments (maintenance-comment overlay) ---------
    "4.13.1": ("comment", "comment", "any", "Information delta", "both", "local",
               "review", "comment-text", "comment-text",
               "constrains 4.13.5; pairs-with 4.13.4"),
    "4.13.2": ("comment", "comment", "any", "Purpose", "both", "local", "candidate",
               "comment-text, declaration-block", "declaration-block",
               "requires 4.13.1"),
    "4.13.3": ("comment", "comment, host-anchor", "any", "Anchor", "exact", "local",
               "candidate", "comment-text, host-anchor-ledger", "host-anchor-ledger",
               "constrains 4.13.9"),
    "4.13.4": ("comment", "comment", "any", "Basis", "exact", "document", "review",
               "comment-text, evidence-ledger", "comment-text",
               "requires 4.13.1; pairs-with 5.4.1"),
    "4.13.5": ("comment", "comment", "any", "any", "exact", "local", "prohibited",
               "comment-text", "none", "requires 4.13.4; pairs-with 7.3.1"),
    "4.13.6": ("comment", "comment", "any", "any", "exact", "local", "prohibited",
               "comment-text", "none", "pairs-with 7.3.1"),
    "4.13.7": ("comment", "comment, removal-condition", "any", "Lifecycle", "exact",
               "local", "candidate", "comment-text, declaration-block",
               "declaration-block", "constrains 4.13.8"),
    "4.13.8": ("comment", "marker", "any", "Comment text", "exact", "local",
               "candidate", "comment-text", "comment-text", "requires 4.13.7"),
    "4.13.9": ("comment-set", "comment", "any", "any", "plain", "document",
               "candidate", "comment-text, host-anchor-ledger", "none",
               "overrides 4.12.1 (hosted comment-set scan path); requires 4.13.3"),

    # --- Part 5: mathematical and empirical content -------------------------
    "5.1.1": ("chunk", "claim", "any", "any", "both", "neighboring", "prohibited",
              "chunk-text, exact-item-ledger", "none", "constrains 5.1.2"),
    "5.1.2": ("chunk", "cross-reference, claim", "any", "any", "both", "document",
              "candidate", "chunk-text, exact-item-ledger",
              "chunk-text, cross-reference-ledger", "requires 5.1.1"),
    "5.2.1": ("symbol", "symbol", "any", "any", "exact", "document", "review",
              "chunk-text, symbol-ledger", "chunk-text, symbol-ledger",
              "requires 2.3.1; constrains 5.2.2"),
    "5.2.2": ("symbol", "symbol", "any", "any", "exact", "document", "review",
              "chunk-text, symbol-ledger", "symbol-ledger",
              "requires 5.2.1; pairs-with 2.1.1"),
    "5.2.3": ("table", "symbol, table", "any", "any", "exact", "document", "candidate",
              "symbol-ledger", "chunk-text, symbol-ledger", "requires 5.2.1"),
    "5.3.1": ("equation", "equation", "any", "any", "both", "local", "review",
              "chunk-text", "chunk-text", "requires 5.2.1"),
    "5.3.2": ("equation", "equation", "any", "any", "exact", "local", "candidate",
              "chunk-text", "chunk-text", "requires 5.3.1; pairs-with 3.1.3"),
    "5.4.1": ("chunk", "claim, measurement", "claim, evidence", "any", "exact",
              "document", "review", "chunk-text, evidence-ledger",
              "chunk-text, evidence-ledger", "constrains 5.4.2; pairs-with 5.6.2"),
    "5.4.2": ("sentence", "quantity", "any", "any", "exact", "local", "review",
              "chunk-text, evidence-ledger", "chunk-text", "requires 5.4.1"),
    "5.4.3": ("citation", "citation", "any", "any", "exact", "document", "prohibited",
              "citation-ledger", "none", "constrains 5.4.4"),
    "5.4.4": ("citation", "citation, claim", "any", "any", "exact", "collection",
              "prohibited", "citation-ledger, claim-ledger", "none", "requires 5.4.3"),
    "5.4.5": ("sentence", "citation", "any", "any", "exact", "local", "candidate",
              "chunk-text, citation-ledger", "chunk-text",
              "requires 5.4.3; pairs-with 2.6.8"),
    "5.5.1": ("figure", "figure", "any", "any", "exact", "local", "review",
              "figure-ledger", "figure-ledger", "constrains 5.5.2"),
    "5.5.2": ("figure", "figure, table", "any", "any", "both", "local", "candidate",
              "chunk-text, figure-ledger", "chunk-text, figure-ledger",
              "requires 5.5.1"),
    "5.5.3": ("figure", "figure, admitted-term", "any", "any", "plain", "document",
              "review", "figure-ledger, term-ledger", "figure-ledger",
              "requires 2.3.1"),
    "5.6.1": ("sentence", "claim", "claim, interpretation", "any", "exact", "local",
              "candidate", "chunk-text, claim-ledger", "chunk-text",
              "constrains 5.6.2; pairs-with 3.9.2"),
    "5.6.2": ("sentence", "claim", "claim, interpretation", "any", "exact", "document",
              "prohibited", "chunk-text, claim-ledger, evidence-ledger", "none",
              "requires 5.6.1"),
    "5.7.1": ("term", "statistic", "any", "any", "exact", "document", "review",
              "chunk-text, term-ledger", "chunk-text, term-ledger", "requires 2.3.1"),
    "5.7.2": ("sentence", "statistic", "any", "any", "both", "document", "review",
              "chunk-text", "chunk-text", "requires 5.7.1"),
    "5.8.1": ("document", "section", "any", "Reproducibility or verification", "exact",
              "document", "candidate", "chunk-text, skeleton-order", "chunk-text",
              "requires 4.3.3"),
    "5.8.2": ("section", "section", "any", "Reproducibility or verification", "plain",
              "document", "review", "chunk-text, term-ledger", "chunk-text",
              "requires 5.8.1"),
    "5.9.1": ("document", "section", "any", "Definition of done", "exact", "document",
              "candidate", "heading, skeleton-order", "heading", "requires 4.3.3"),
    "5.9.2": ("chunk", "requirement", "requirement", "any", "exact", "local", "review",
              "chunk-text, exact-item-ledger", "chunk-text", "requires 5.9.1"),
    "5.9.3": ("chunk", "requirement", "requirement", "any", "exact", "document",
              "mechanical", "chunk-text, exact-item-ledger",
              "chunk-text, exact-item-ledger", "requires 5.9.2"),
    "5.9.4": ("document", "parent-link", "any", "any", "exact", "collection", "review",
              "chunk-text, evidence-ledger", "chunk-text", "requires 5.9.3"),
    "5.9.5": ("document", "requirement", "any", "any", "exact", "document", "review",
              "chunk-text", "chunk-text", "requires 5.9.2"),
    "5.9.6": ("document", "requirement", "any", "any", "exact", "collection",
              "prohibited", "chunk-text", "none", "requires 5.9.5"),
    "5.9.7": ("document", "invariant", "any", "any", "exact", "collection", "review",
              "chunk-text, exact-item-ledger", "chunk-text", "requires 4.11.8"),
    "5.9.8": ("document", "requirement", "any", "any", "exact", "collection",
              "prohibited", "chunk-text", "none", "requires 5.9.2"),

    # --- Part 6: explanatory devices ----------------------------------------
    "6.1.1": ("chunk", "analogy", "mechanism", "any", "plain", "local", "review",
              "chunk-text, term-ledger", "chunk-text", "requires 2.2.1"),
    "6.1.2": ("chunk", "analogy", "mechanism", "any", "plain", "local", "review",
              "chunk-text", "chunk-text", "requires 6.1.1"),
    "6.1.3": ("chunk", "analogy", "mechanism", "any", "plain", "document", "review",
              "chunk-text", "chunk-text", "requires 6.1.1"),
    # `any`, not `worked-example`: the rule requires the worked example to
    # exist, so scoping it to that construct would delete the rule from the
    # documents that omit one. Its trigger is a central mechanism.
    "6.2.1": ("chunk", "any", "mechanism", "any", "plain", "section",
              "review", "chunk-text", "chunk-text", "pairs-with 5.3.1"),
    "6.2.2": ("chunk", "worked-example", "mechanism", "any", "plain", "local",
              "candidate", "chunk-text", "chunk-text", "requires 6.2.1"),
    "6.2.3": ("chunk", "worked-example", "mechanism", "any", "plain", "local", "review",
              "chunk-text", "chunk-text", "requires 6.2.1"),
    "6.3.1": ("bounded-block", "bounded-block", "any", "any", "plain", "local",
              "mechanical", "chunk-text", "chunk-text", "requires 4.6.2"),
    "6.3.2": ("bounded-block", "bounded-block, requirement", "any", "any", "exact",
              "document", "prohibited", "chunk-text, exact-item-ledger", "none",
              "requires 6.3.1"),
    "6.3.3": ("document", "bounded-block", "any", "any", "both", "document", "review",
              "chunk-text", "chunk-text", "requires 6.3.1; pairs-with 4.6.3"),
    # `any`, not `diagram`: the rule requires a diagram for a structure that
    # has none. Its trigger is the diagram-trigger structure defined above it.
    "6.4.1": ("figure", "any", "any", "any", "plain", "section", "review",
              "chunk-text, figure-ledger", "figure-ledger", "pairs-with 6.4.2"),
    "6.4.2": ("figure", "diagram, cross-reference", "any", "any", "plain", "document",
              "mechanical", "chunk-text, figure-ledger, cross-reference-ledger",
              "chunk-text", "requires 6.4.1"),
    "6.4.3": ("figure", "diagram, admitted-term", "any", "any", "plain", "document",
              "review", "figure-ledger, term-ledger", "figure-ledger",
              "requires 2.3.1"),
    "6.4.4": ("figure", "diagram", "any", "any", "plain", "local", "candidate",
              "figure-ledger", "figure-ledger", "requires 6.4.3"),
    "6.5.1": ("sentence", "admitted-term, claim", "any", "any", "both", "document",
              "review", "chunk-text, term-ledger, claim-ledger", "chunk-text",
              "requires 2.1.2"),
    "6.5.2": ("sentence", "admitted-term", "any", "any", "plain", "document",
              "candidate", "chunk-text, term-ledger", "chunk-text", "requires 6.5.1"),
    "6.5.3": ("section", "section", "any", "any", "plain", "section", "candidate",
              "chunk-text, term-ledger", "chunk-text", "requires 6.5.2"),
    "6.5.4": ("chunk", "prohibited-phrase", "any", "any", "plain", "section",
              "candidate", "chunk-text", "chunk-text", "pairs-with 4.2.3"),

    # --- Part 7: limitations, caveats, interpretation -----------------------
    # `any`, not `limitation`: the rule requires boundary material to exist,
    # so a document with none would drop the rule that demands it. Its
    # trigger is the governed document.
    "7.1.1": ("document", "any", "limitation", "any", "exact", "document",
              "candidate", "chunk-text, skeleton-order", "chunk-text",
              "requires 4.3.3"),
    "7.1.2": ("chunk", "limitation", "limitation", "any", "exact", "document", "review",
              "chunk-text", "chunk-text", "requires 7.1.1"),
    "7.1.3": ("chunk", "limitation, risk", "limitation, risk", "any", "exact",
              "document", "review", "chunk-text", "chunk-text", "requires 7.1.1"),
    "7.1.4": ("chunk", "limitation", "limitation", "any", "exact", "document", "review",
              "chunk-text, evidence-ledger", "chunk-text", "requires 7.1.1"),
    "7.1.5": ("chunk", "limitation, measurement", "limitation", "any", "exact",
              "document", "review", "chunk-text, evidence-ledger", "chunk-text",
              "requires 7.1.1"),
    "7.1.6": ("chunk", "limitation", "limitation", "any", "exact", "document", "review",
              "chunk-text", "chunk-text", "requires 7.1.1; requires 7.1.2"),
    "7.2.1": ("chunk", "caveat, claim", "claim", "any", "exact", "neighboring",
              "review", "chunk-text, claim-ledger", "chunk-text", "constrains 7.2.2"),
    "7.2.2": ("document", "caveat", "limitation", "any", "exact", "document", "review",
              "chunk-text", "chunk-text", "requires 7.2.1"),
    "7.3.1": ("chunk", "observation", "evidence, interpretation", "any", "exact",
              "local", "review", "chunk-text, evidence-ledger", "chunk-text",
              "requires 4.1.1"),
    "7.3.2": ("bounded-block", "speculation", "any", "any", "exact", "local",
              "mechanical", "chunk-text", "chunk-text", "requires 4.6.2"),
    "7.3.3": ("bounded-block", "speculation", "any", "any", "exact", "local",
              "candidate", "chunk-text, claim-ledger", "chunk-text",
              "requires 7.3.2; requires 5.6.1"),
    "7.4.1": ("sentence", "generalization", "any", "any", "exact", "document", "review",
              "chunk-text, claim-ledger", "chunk-text", "requires 7.1.2"),
    "7.4.2": ("sentence", "generalization, claim", "any", "any", "exact", "document",
              "candidate", "chunk-text, claim-ledger", "chunk-text",
              "requires 7.4.1; requires 5.6.1"),

    # --- Part 8: textual conformance and machine checking -------------------
    "8.2.1": ("conformance-record", "tool-artifact", "any", "any", "both",
              "document", "mechanical", "conformance-record",
              "conformance-record", "requires 8.2.2; pairs-with 8.6.6"),
    "8.2.2": ("conformance-record", "tool-artifact", "any", "any", "both",
              "document", "mechanical", "conformance-record",
              "conformance-record", "validates 8.2.1"),
    "8.2.3": ("conformance-record", "declaration", "any", "any", "both",
              "document", "mechanical",
              "declaration-block, conformance-record", "conformance-record",
              "requires 4.3.1; pairs-with 8.6.2"),
    "8.2.5": ("conformance-record", "tool-artifact", "any", "any", "both",
              "document", "mechanical", "conformance-record",
              "conformance-record", "constrains 8.2.1; pairs-with 8.6.6"),
    "8.6.1": ("conformance-record", "tool-artifact", "any", "any", "both",
              "collection", "mechanical", "conformance-record",
              "conformance-record", "pairs-with 8.6.2"),
    "8.6.2": ("conformance-record", "tool-artifact", "any", "any", "both",
              "collection", "mechanical", "conformance-record", "none",
              "requires 8.6.1; pairs-with 8.2.3"),
    "8.6.6": ("conformance-record", "tool-artifact", "any", "any", "both",
              "document", "mechanical", "conformance-record",
              "conformance-record", "requires 8.2.1; requires 8.2.5"),
}
# fmt: on


def metadata_lines(rule_id: str) -> list[str]:
    """Render the four §1.6 metadata lines for one rule."""
    if rule_id not in ANNOTATIONS:
        raise KeyError(f"no curated navigation metadata for rule {rule_id}")
    (
        target,
        constructs,
        chunks,
        slots,
        layers,
        context,
        rewrite,
        reads,
        writes,
        relations,
    ) = ANNOTATIONS[rule_id]
    return [
        f"**Constructs:** {constructs}",
        f"**Navigation:** target: {target} · chunks: {chunks} · slots: {slots}"
        f" · layers: {layers} · context: {context} · rewrite: {rewrite}",
        f"**Resources:** reads: {reads} · writes: {writes}",
        f"**Relations:** {relations}",
    ]
